# Generated by Django 3.2.1 on 2021-11-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211127_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='room',
            name='admin',
        ),
    ]
